<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiTech.Platform.Application\MultiTech.Platform.Application.csproj" />
    <ProjectReference Include="..\MultiTech.Platform.Infrastructure\MultiTech.Platform.Infrastructure.csproj" />
    <ProjectReference Include="..\MultiTech.Platform.Contracts\MultiTech.Platform.Contracts.csproj" />
  </ItemGroup>

</Project>
